server:
  port: 80
  servlet:
    context-path: /iclassroom
    session:
      persistent: true
      store-dir: ./session
     
spring:
  mvc:
    view:
      prefix: /html/
      suffix: .html
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai 
  resources:
    static-locations: ./static
